### ISSUE TITLE
I found a bug[crash on launch 1.15.2-fabric]

### ISSUE THREAD

**Issue by SDUBZ** [squid233/SquidCraft#10]
**Minecraft and SquidCraft version**

minecraft:1.15.2
SquidCraft-1.15.2-0.4.8

**Crash report**
https://gist.github.com/SDUBZ/d63a102277dc2b3ce2f91c4a95290580

https://gist.githubusercontent.com/SDUBZ/ae3e2d7f38b66c0764f060a081bbd46f/raw/243c71403a8553fa3f120c1cac0abc81cde75fd1/latest.log
**Additional context**

**Comment by squid233** [comment]
Please only add SquidCraft. We need more info.
