### ISSUE TITLE
发现Bug：当为鱿鱼工具添加附魔时，附魔光效渲染位置错误

### ISSUE THREAD

**Issue by teddyxlandlee** [squid233/SquidCraft#12]
**Minecraft 与 鱿鱼工艺 的版本**
MC版本：1.16.1
Mod版本：0.1.0

**漏洞症状**
当为鱿鱼工具附魔时，附魔光效渲染位置错误，在透明像素的位置也有附魔光效的渲染。

**Comment by squid233** [comment]
正常，因为鱿鱼工具带有半透明像素。
