### ISSUE TITLE
关于新特性的讨论

### ISSUE THREAD

**Issue by squid233** [squid233/SquidCraft#8]
我们现在需要决定出哪些新的特性。请各位玩家共同讨论。讨论结束后我们会开始进入投票环节。

**Comment by baka4n** [comment]
多出点bug[/doge]

**Comment by squid233** [comment]
:dog:

**Comment by ScarletVirus** [comment]
现在还能投票吗 偶建议出个新维度 或者新群系 里面的方块都是鱿鱼方块 望采纳

**Comment by squid233** [comment]
新维度可以，不过群系有些复杂 到时候我想想办法添加

**Comment by ScarletVirus** [comment]
建议改成：精 神 污 染 维 度

**Comment by squid233** [comment]
hhhc

**Comment by crazy-piggy** [comment]
这个squidcraft:milk_bucket写了有用吗QwQ
有一个minecraft:milk_bucket就够了awa

**Comment by squid233** [comment]
> 这个squidcraft:milk_bucket写了有用吗QwQ
> 有一个minecraft:milk_bucket就够了awa

原版的牛奶桶并没有绑定牛奶液体
所以需要自己添加
